config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  get '/lyrics/public' => 'lyrics#public'
  get '/lyrics/landing' => 'lyrics#landing'
  root 'lyrics#landing'
  resources :lyrics


end

app/models/lyric.rb
class Lyric < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :lyrics
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lyrics_controller.rb
class LyricsController < ApplicationController
	before_filter :authenticate_user!
	
	def index
		@lyrics = Lyric.all
	end

	def landing
		@lyrics = Lyric.all
	end

	def public
		@lyrics = Lyric.all
	end

	def show
		@lyric = Lyric.find(params[:id])
	end

	def new
		@lyric = Lyric.new
	end

	def create
		
		@lyric = Lyric.new(lyric_params)
		@lyric.user = User.find(current_user.id)
		if @lyric.save
			redirect_to @lyric
		else
			redner 'new'
		end
	end
	
	def edit
		@lyric = Lyric.find(params[:id])
		
	end

	def update
		@lyric = Lyric.find(params[:id])

		if @lyric.update(lyric_params)
    	redirect_to @lyric
 		else
    	render 'edit'
	   end
	end

	def destroy
		@lyric= Lyric.find(params[:id])
		@lyric.destroy

		redirect_to lyrics_path
	end

private

	def lyric_params
		params.require(:lyric).permit(:song, :verse1, :chorus, :verse2, :bridge, :public)	
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lyrics_helper.rb
module LyricsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lyriclyric</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= lyrics_landing_path %>">Songy</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="<%= lyrics_path %>">Your Songs<span class="sr-only">(current)</span></a></li>
        <li><a href="/lyrics/new">New Song</a></li>
        <li><a href="/lyrics/public">Collab</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Tools<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Pitch Pipe (Coming Soon!)</a></li>
            <li class="divider"></li>
            <li><a href="#">More JS fun (Coming Soon!)</a></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete%></li>
      </ul>
    </div>
  </div>
</nav>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/lyrics/edit.html.erb
<%= form_for @lyric do |f| %>
	<div class="form-group">
    	<div class="col-md-4 col-md-offset-4">
			<%= f.label :song, class: "control-label" %>
		</div>
		<div class="col-md-4 col-md-offset-4">
			<%= f.text_field :song, class: "form-control"%>
		</div>
	</div>

	<div class="form-group">
    	<div class="col-md-4 col-md-offset-4">
			<%= f.label :verse1, class: "control-label" %>
		</div>
		<div class="col-md-4 col-md-offset-4">
			<%= f.text_area :verse1, class: "form-control", rows: "6"%>
		</div>
	</div>

	<div class="form-group">
    	<div class="col-md-4 col-md-offset-4">
			<%= f.label :chorus, class: "control-label" %>
		</div>
		<div class="col-md-4 col-md-offset-4">
			<%= f.text_area :chorus, class: "form-control", rows: "6"%>
		</div>
	</div>

	<div class="form-group">
    	<div class="col-md-4 col-md-offset-4">
			<%= f.label :verse2, class: "control-label" %>
		</div>
		<div class="col-md-4 col-md-offset-4">
			<%= f.text_area :verse2, class: "form-control", rows: "6"%>
		</div>
	</div>

	<div class="form-group">
    	<div class="col-md-4 col-md-offset-4">
			<%= f.label :bridge, class: "control-label" %>
		</div>
		<div class="col-md-4 col-md-offset-4">
			<%= f.text_area :bridge, class: "form-control", rows: "6"%>
		</div>
	</div>

	<%if current_user.id == @lyric.user_id%>
		<div class="form-group">
	    	<div class="col-md-4 col-md-offset-4">
				<%= label_tag(:public, "Make this Lyric Public", class: "control-label") %>
			</div>
			<div class="col-md-4 col-md-offset-4">
				<%= f.check_box :public, class: "form-control"%>
			</div>
		</div>
	<%end%>

	<div class="form-group">
		<div class="col-md-4 col-md-offset-4">
			<%= f.submit "Save Song", class: "btn btn-primary" %>
			<%=link_to "Back", lyrics_path, class: "btn btn-default"%>
		</div>
	</div>
<%end%>

app/views/lyrics/index.html.erb
<div class="jumbotron" style="padding-left:35px; padding-right:35px;">
  <h1>Your Lyrics</h1>
  <p>Click on your Song to view it or start a New Lyric</p>
  <p><a href="<%=new_lyric_path%>" class="btn btn-primary btn-lg">New Lyric</a></p>
</div>

	<div class="col-sm-6 col-md-offset-5">
		<%@lyrics.each do |lyric|%>
				<div class="row">
					<div class="col-sm-4">
						<%if current_user.id == lyric.user_id%>
							<%= link_to lyric.song, lyric, class: "btn btn-default text-center"%>
						<%end%>
					</div>
				</div>
		<%end%>
	</div>

app/views/lyrics/landing.html.erb
<div class="jumbotron" style="padding-left:35px; padding-right:35px;">
  <h1>Your Lyrics</h1>
  <p>Click on your Song to view it or start a New Lyric</p>
  <p><a href="<%=new_lyric_path%>" class="btn btn-primary btn-lg">New Lyric</a></p>
</div>

	<div class="col-sm-6 col-md-offset-5">
		<%@lyrics.each do |lyric|%>
				<div class="row">
					<div class="col-sm-4">
						<%if current_user.id == lyric.user_id%>
							<%= link_to lyric.song, lyric, class: "btn btn-default text-center"%>
						<%end%>
					</div>
				</div>
		<%end%>
	</div>

app/views/lyrics/new.html.erb
<%= form_for :lyric, url: lyrics_path, :html => {:class => "form-horizontal center"} do |f| %>
	<div class="form-group">
    	<div class="col-md-4 col-md-offset-4">
			<%= f.label :song, class: "control-label" %>
		</div>
		<div class="col-md-4 col-md-offset-4">
			<%= f.text_field :song, class: "form-control"%>
		</div>
	</div>

	<div class="form-group">
    	<div class="col-md-4 col-md-offset-4">
			<%= f.label :verse1, class: "control-label" %>
		</div>
		<div class="col-md-4 col-md-offset-4">
			<%= f.text_area :verse1, class: "form-control", rows: "6"%>
		</div>
	</div>

	<div class="form-group">
    	<div class="col-md-4 col-md-offset-4">
			<%= f.label :chorus, class: "control-label" %>
		</div>
		<div class="col-md-4 col-md-offset-4">
			<%= f.text_area :chorus, class: "form-control", rows: "6"%>
		</div>
	</div>

	<div class="form-group">
    	<div class="col-md-4 col-md-offset-4">
			<%= f.label :verse2, class: "control-label" %>
		</div>
		<div class="col-md-4 col-md-offset-4">
			<%= f.text_area :verse2, class: "form-control", rows: "6"%>
		</div>
	</div>

	<div class="form-group">
    	<div class="col-md-4 col-md-offset-4">
			<%= f.label :bridge, class: "control-label" %>
		</div>
		<div class="col-md-4 col-md-offset-4">
			<%= f.text_area :bridge, class: "form-control", rows: "6"%>
		</div>
	</div>

	<div class="form-group">
    	<div class="col-md-4 col-md-offset-4">
			<%= label_tag(:public, "Make this Lyric Public", class: "control-label") %>
		</div>
		<div class="col-md-4 col-md-offset-4">
			<%= f.check_box :public, class: "form-control"%>
		</div>
	</div>

	<div class="form-group">
		<div class="col-md-4 col-md-offset-4">
			<%= f.submit "Save Song", class: "btn btn-primary" %>
			<%=link_to "Back", lyrics_path, class: "btn btn-default"%>
		</div>
	</div>
<%end%>

app/views/lyrics/public.html.erb
<div class="col-sm-4 col-md-offset-4">
	<%@lyrics.where(public: true).each do |lyric|%>
			<%= link_to lyric.song, lyric, class: "btn btn-default text-center"%></br>
	<%end%>
</div>

app/views/lyrics/show.html.erb
<div class="row">
	<div class="btn-group-vertical col-sm-1">
	    <a href="<%=edit_lyric_path%>" class="btn btn-default">Edit</a>
	    <a href="<%=lyrics_path%>" class="btn btn-default">Back</a>
	  	<%= link_to 'Delete', lyric_path, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default"%>
	</div>
	<div class="col-sm-4 col-md-offset-3">
		<h5>Song</h5>
		<div class="well text-center"><%=@lyric.song%></div>
	</div>
</div>

<div class="row">
	<div class="col-sm-4 col-md-offset-4">
		<h5>Verse 1</h5>
		<div class="well text-center"><%=@lyric.verse1%></div>
	</div>
</div>

<div class="row">
	<div class="col-sm-4 col-md-offset-4">
		<h5>Chorus</h5>
		<div class="well text-center"><%=@lyric.chorus%></div>
	</div>
</div>

<div class="row">
	<div class="col-sm-4 col-md-offset-4">
		<h5>Verse 2</h5>
		<div class="well text-center"><%=@lyric.verse2%></div>
	</div>
</div>

<div class="row">
	<div class="col-sm-4 col-md-offset-4">
		<h5>Bridge</h5>
		<div class="well text-center"><%=@lyric.bridge%></div>
	</div>
</div>
<div class="row">
	<div class="col-sm-4 col-md-offset-4">
		<h5>Bridge</h5>
		<div class="well text-center">
			<%if @lyric.public == true%>
				<h1> This is a public Lyric! </h1>
			<%else%>
				<h1> This Lyric is Private</h1>
			<%end%>
		</div>
	</div>
</div>